name: place_pickarte
description: Sophisticated, artistic, pixel-by-pixel customizable map place picker for Flutter supporting Google Maps, Mapbox, OpenStreetMap and others.
version: 0.2.1
homepage: https://kamranbekirov.com
repository: https://github.com/kamranbekirovyz/place-pickarte

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1
  rxdart: ^0.27.5
  geolocator: ^11.0.0
  http: ^1.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter: