name: place_pickarte
description: A new Flutter project.
version: 0.0.1
homepage: https://kamranbekirov.com
repository: https://github.com/kamranbekirovyz/place-pickarte

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1
  rxdart: ^0.27.5
  geolocator: ^9.0.2
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter: